name: Chatbot Feature Unit and Integration Testing

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x 

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test chatbot_implementation.test.js
